### ISSUE TITLE
Not saving credentials

### ISSUE THREAD

**Issue by looreen** [2DegreesInvesting/ds-incubator#2]
After the meeting earlier today, I followed the instructions given in the book. It seems I can't save my credentials. I tried the procedure described here several times, but I am asked every time to enter credentials.

**Comment by maurolepore** [comment]
(Relates to #1)

Thanks @looreen for your feedback. From slack I understand you are on Windows. I don't know exactly what's wrong but we could explore some ideas to get closer to the problem.



#### 1. Is your version of Git recent?

Automatic credentials management was apparently added to Git relatively recently ([10.1 You might not need to do anything!](https://happygitwithr.com/credential-caching.html)).


On a Git Bash terminal run this:

```
git --version
```



#### 2. What is the output of `git config --global credential.helper`?

On a Git Bash terminal run this. 

```
git config --global credential.helper
```

I expect the output to be _manager_. If not run this:

```
git config --global credential.helper "manager"
git config --global credential.helper
```

I expect the output to be _manager_.

Also, What is the output of this?"

```
git config --show-origin --get credential.helper
```

Jenny Bryan gets this output:

```
file:C:/Program Files/Git/mingw64/etc/gitconfig manager
```

I get this output:

```
file:C:/Users/Mauro/.gitconfig  manager
```

#### 3. Do you see git credentials stored under _Control Panel\User Accounts\Credential Manager_?

Maybe you want to remove the credentials, then commit and push to trigger the credentials' challenge, then check again if credentials were added at _Control Panel\User Accounts\Credential Manager_.

![image](https://user-images.githubusercontent.com/5856545/66854320-8095b980-ef57-11e9-8f19-afce72ca8d06.png)

#### Notes

In our organization, the only person that seems to be using two-factor authentication is @cjyetman. 

![image](https://user-images.githubusercontent.com/5856545/66855504-bb98ec80-ef59-11e9-9ab0-454ae7ccc4a6.png)

So, (a) we can for now discard that as the source of the problem, and (b) it'll be nice to hear CJ's advice on the topic.

--

I look forward to the results of your experiments. I hope this brings us closer to solving your problem.

**Comment by maurolepore** [comment]
Closing now to keep open issues mostly focused on meetups and proposed topics. If need to, feel free to reopen.
